name: clima_data
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dartz: 0.9.2
  http: 0.12.2
  connectivity: 2.0.1
  riverpod: 0.12.2
  shared_preferences: ^0.5.12+4

  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain

dev_dependencies:
  test: ^1.14.4
  lint: ^1.4.0-dev.d210.1
