name: clima_data
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clima_core:
    path: ../clima_core
  clima_domain:
    path: ../clima_domain

  connectivity: ^3.0.3
  dartz: ^0.10.0-nullsafety.1

  flutter:
    sdk: flutter

  http: ^0.13.2
  riverpod: ^0.14.0+3
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3
  test: ^1.16.5
